//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobProcessor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceData
    {
        public int Id { get; set; }
        public string DeviceId { get; set; }
        public System.DateTime SendDateTime { get; set; }
        public decimal Temperature { get; set; }
        public decimal Humidity { get; set; }
        public decimal PM25 { get; set; }
    }
}
